# Generated by Django 4.0.2 on 2022-02-12 08:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mardikor', '0004_advertisement_condition_advertisement_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/categoryImg'),
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('about', ckeditor.fields.RichTextField()),
                ('experience', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('address', ckeditor.fields.RichTextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mardikor.category')),
            ],
        ),
    ]
