# Generated by Django 4.0.2 on 2022-02-12 09:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mardikor', '0006_employer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='title',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
